// <auto-generated />
using System;
using Medix.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medix.API.Migrations
{
    [DbContext(typeof(MedixContext))]
    [Migration("20251010161328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleCategory", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArticleId", "CategoryId")
                        .HasName("PK__ArticleC__3DF2E3485EBA2F42");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategories", (string)null);
                });

            modelBuilder.Entity("Medix.API.Data.Models.AisymptomAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Emrtext")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMRText");

                    b.Property<bool>("IsGuestSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PossibleConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedAction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RecommendedSpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedEmrurl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UploadedEMRUrl");

                    b.HasKey("Id")
                        .HasName("PK__AISympto__3214EC07B9D05D40");

                    b.HasIndex("RecommendedSpecializationId");

                    b.HasIndex(new[] { "PatientId", "CreatedAt" }, "IX_AISymptomAnalysis_Patient_Date")
                        .HasFilter("([IsGuestSession]=(0))");

                    b.HasIndex(new[] { "SessionId" }, "IX_AISymptomAnalysis_SessionId")
                        .IsUnique();

                    b.HasIndex(new[] { "SessionId" }, "UQ__AISympto__C9F4929187A0808A")
                        .IsUnique();

                    b.ToTable("AISymptomAnalysis", (string)null);
                });

            modelBuilder.Entity("Medix.API.Data.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AisymptomAnalysisId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AISymptomAnalysisId");

                    b.Property<DateTime>("AppointmentEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("MedicalInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("RefundProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("None");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Appointm__3214EC07ACA2C226");

                    b.HasIndex("AisymptomAnalysisId");

                    b.HasIndex(new[] { "DoctorId", "Status", "AppointmentStartTime" }, "IX_Appointments_Doctor_Status_Date");

                    b.HasIndex(new[] { "PatientId", "Status", "AppointmentStartTime" }, "IX_Appointments_Patient_Status_Date");

                    b.HasIndex(new[] { "PaymentStatus" }, "IX_Appointments_Payment_Status")
                        .HasFilter("([PaymentStatus]='Pending')");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Medix.API.Data.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07F4846A67");

                    b.HasIndex(new[] { "EntityType", "EntityId", "Timestamp" }, "IX_AuditLogs_Entity_Date");

                    b.HasIndex(new[] { "UserId", "Timestamp" }, "IX_AuditLogs_User_Date");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Cmspage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageSlug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CMSPages__3214EC07C4D930A8");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "PageSlug" }, "UQ__CMSPages__7D9ACA7592E447C6")
                        .IsUnique();

                    b.ToTable("CMSPages", (string)null);
                });

            modelBuilder.Entity("Medix.API.Data.Models.ContentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__ContentC__3214EC07D8126E96");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Name" }, "UQ__ContentC__737584F6163A8C93")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "UQ__ContentC__BC7B5FB6F407996B")
                        .IsUnique();

                    b.ToTable("ContentCategories");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Education")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAcceptingAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ServiceTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Doctors__3214EC07E752F941");

                    b.HasIndex(new[] { "ServiceTierId", "IsVerified", "IsAcceptingAppointments" }, "IX_Doctors_ServiceTier_Verified");

                    b.HasIndex(new[] { "SpecializationId", "IsVerified", "IsAcceptingAppointments" }, "IX_Doctors_Specialization_Verified");

                    b.HasIndex(new[] { "UserId" }, "UQ__Doctors__1788CC4D72D3D584")
                        .IsUnique();

                    b.HasIndex(new[] { "LicenseNumber" }, "UQ__Doctors__E8890166F082D2A2")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorAdCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Clicks")
                        .HasColumnType("int");

                    b.Property<int>("Conversions")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<decimal>("DailySpendLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impressions")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TargetSpecializations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__DoctorAd__3214EC0767419EB5");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAdCampaigns");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorPerformanceMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<decimal>("CancellationRate")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int>("CompletedAppointments")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PatientSatisfactionScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("ResponseTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DoctorPe__3214EC07B63014E7");

                    b.HasIndex(new[] { "DoctorId", "MetricDate" }, "IX_DoctorPerformanceMetrics_Doctor_Date");

                    b.HasIndex(new[] { "DoctorId", "MetricDate" }, "UK_DoctorPerformanceMetrics_Doctor_Date")
                        .IsUnique();

                    b.ToTable("DoctorPerformanceMetrics");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("CommissionDeductions")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__DoctorSa__3214EC07A1F51712");

                    b.HasIndex(new[] { "DoctorId", "PeriodStartDate", "PeriodEndDate" }, "IX_DoctorSalaries_Doctor_Period");

                    b.ToTable("DoctorSalaries");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__DoctorSc__3214EC0711B7EC7E");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorScheduleOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("OverrideDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__DoctorSc__3214EC07B3CCF936");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorScheduleOverrides");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorServiceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("ConsultationFeeMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxDailyAppointments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PriorityBoost")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DoctorSe__3214EC079BB52A75");

                    b.HasIndex(new[] { "Name" }, "UQ__DoctorSe__737584F6A6BAAA50")
                        .IsUnique();

                    b.ToTable("DoctorServiceTiers");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServicePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DoctorSu__3214EC0720F0598F");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServicePackageId");

                    b.HasIndex(new[] { "Status", "EndDate" }, "IX_DoctorSubscriptions_Status_Date")
                        .HasFilter("([Status]='Active')");

                    b.ToTable("DoctorSubscriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.HealthArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Standard");

                    b.Property<bool>("IsHomepageVisible")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HealthAr__3214EC07E313B440");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "Status", "IsHomepageVisible", "DisplayOrder" }, "IX_HealthArticles_Status_Homepage")
                        .HasFilter("([Status]='Published')");

                    b.HasIndex(new[] { "Slug" }, "UQ__HealthAr__BC7B5FB6544B35AF")
                        .IsUnique();

                    b.ToTable("HealthArticles");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssessmentNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__MedicalR__3214EC07C4F0CA94");

                    b.HasIndex(new[] { "AppointmentId" }, "IX_MedicalRecords_Appointment");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__MedicalR__8ECDFCC3B607BE24")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicalRecordAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__MedicalR__3214EC071BCB6443");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("MedicalRecordAttachments");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicationDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CommonUses")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DosageForms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SideEffects")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__Medicati__3214EC0707AD75F5");

                    b.ToTable("MedicationDatabase", (string)null);
                });

            modelBuilder.Entity("Medix.API.Data.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC078AC294D4");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "IX_Notifications_User_Read");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Patients__3214EC0796AC84F2");

                    b.HasIndex(new[] { "UserId" }, "IX_Patients_User");

                    b.HasIndex(new[] { "UserId" }, "UQ__Patients__1788CC4DED858672")
                        .IsUnique();

                    b.HasIndex(new[] { "MedicalRecordNumber" }, "UQ__Patients__8E549ED07E09C107")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Medix.API.Data.Models.PatientHealthReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RelatedAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__PatientH__3214EC077FF63AEE");

                    b.HasIndex("RelatedAppointmentId");

                    b.ToTable("PatientHealthReminders");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Prescrip__3214EC073F764DCB");

                    b.HasIndex("MedicationId");

                    b.HasIndex(new[] { "MedicalRecordId" }, "IX_Prescriptions_MedicalRecord");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC071547DB8A");

                    b.HasIndex(new[] { "IsActive", "StartDate", "EndDate" }, "IX_Promotions_Active_Date")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex(new[] { "Code" }, "UQ__Promotio__A25C5AA731A4F984")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC075921C4AA");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3214EC078F148276");

                    b.HasIndex(new[] { "AppointmentId" }, "IX_Reviews_Appointment");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__Reviews__8ECDFCC3433D9EE5")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Medix.API.Data.Models.ServicePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceP__3214EC07EBF78F33");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("Medix.API.Data.Models.SiteBanner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BannerTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__SiteBann__3214EC071F600722");

                    b.ToTable("SiteBanners");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Speciali__3214EC078A7C5AFE");

                    b.HasIndex(new[] { "Name" }, "UQ__Speciali__737584F626A610A2")
                        .IsUnique();

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Medix.API.Data.Models.SystemAnalytic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Dimension1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dimension2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("date");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id")
                        .HasName("PK__SystemAn__3214EC07D5127990");

                    b.HasIndex(new[] { "MetricDate", "MetricType" }, "IX_SystemAnalytics_Date_Type");

                    b.ToTable("SystemAnalytics");
                });

            modelBuilder.Entity("Medix.API.Data.Models.SystemConfiguration", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("String");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ConfigKey")
                        .HasName("PK__SystemCo__4A306785E3A5101D");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("Medix.API.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07B418E8B4");

                    b.HasIndex(new[] { "EmailConfirmed", "IsActive" }, "IX_Users_Email_Confirmed")
                        .HasFilter("([EmailConfirmed]=(1))");

                    b.HasIndex(new[] { "Role", "IsActive" }, "IX_Users_Role_Active");

                    b.HasIndex(new[] { "NormalizedEmail" }, "UK_Users_NormalizedEmail")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedUserName" }, "UK_Users_NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("VND");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Wallets__3214EC077C9E6416");

                    b.HasIndex(new[] { "UserId" }, "IX_Wallets_User")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex(new[] { "UserId" }, "UQ__Wallets__1788CC4DFDC5A720")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Medix.API.Data.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__WalletTr__3214EC075209C405");

                    b.HasIndex("RelatedAppointmentId");

                    b.HasIndex(new[] { "TransactionType", "TransactionDate" }, "IX_WalletTransactions_Type_Date");

                    b.HasIndex(new[] { "WalletId", "TransactionDate" }, "IX_WalletTransactions_Wallet_Date")
                        .IsDescending(false, true);

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("ArticleCategory", b =>
                {
                    b.HasOne("Medix.API.Data.Models.HealthArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleCategories_Article");

                    b.HasOne("Medix.API.Data.Models.ContentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleCategories_Category");
                });

            modelBuilder.Entity("Medix.API.Data.Models.AisymptomAnalysis", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Patient", "Patient")
                        .WithMany("AisymptomAnalyses")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_AISymptomAnalysis_Patient");

                    b.HasOne("Medix.API.Data.Models.Specialization", "RecommendedSpecialization")
                        .WithMany("AisymptomAnalyses")
                        .HasForeignKey("RecommendedSpecializationId")
                        .HasConstraintName("FK_AISymptomAnalysis_Specialization");

                    b.Navigation("Patient");

                    b.Navigation("RecommendedSpecialization");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Appointment", b =>
                {
                    b.HasOne("Medix.API.Data.Models.AisymptomAnalysis", "AisymptomAnalysis")
                        .WithMany("Appointments")
                        .HasForeignKey("AisymptomAnalysisId")
                        .HasConstraintName("FK_Appointments_AISymptomAnalysis");

                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Doctor");

                    b.HasOne("Medix.API.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Patient");

                    b.Navigation("AisymptomAnalysis");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medix.API.Data.Models.AuditLog", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Cmspage", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "Author")
                        .WithMany("Cmspages")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_CMSPages_Author");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medix.API.Data.Models.ContentCategory", b =>
                {
                    b.HasOne("Medix.API.Data.Models.ContentCategory", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_ContentCategories_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Doctor", b =>
                {
                    b.HasOne("Medix.API.Data.Models.DoctorServiceTier", "ServiceTier")
                        .WithMany("Doctors")
                        .HasForeignKey("ServiceTierId")
                        .HasConstraintName("FK_Doctors_ServiceTier");

                    b.HasOne("Medix.API.Data.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Specialization");

                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Medix.API.Data.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_User");

                    b.Navigation("ServiceTier");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorAdCampaign", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorAdCampaigns")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorAdCampaigns_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorPerformanceMetric", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorPerformanceMetrics")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorPerformanceMetrics_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSalary", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorSalaries")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSalaries_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSchedule", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSchedules_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorScheduleOverride", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorScheduleOverrides")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DoctorScheduleOverrides_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorSubscription", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorSubscriptions")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSubscriptions_Doctor");

                    b.HasOne("Medix.API.Data.Models.ServicePackage", "ServicePackage")
                        .WithMany("DoctorSubscriptions")
                        .HasForeignKey("ServicePackageId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSubscriptions_ServicePackage");

                    b.Navigation("Doctor");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("Medix.API.Data.Models.HealthArticle", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "Author")
                        .WithMany("HealthArticles")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_HealthArticles_Author");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicalRecord", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Medix.API.Data.Models.MedicalRecord", "AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecords_Appointment");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicalRecordAttachment", b =>
                {
                    b.HasOne("Medix.API.Data.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("MedicalRecordAttachments")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecordAttachments_MedicalRecord");

                    b.HasOne("Medix.API.Data.Models.User", "UploadedByNavigation")
                        .WithMany("MedicalRecordAttachments")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecordAttachments_Uploader");

                    b.Navigation("MedicalRecord");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Notification", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Patient", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Medix.API.Data.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Patients_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.PatientHealthReminder", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Appointment", "RelatedAppointment")
                        .WithMany("PatientHealthReminders")
                        .HasForeignKey("RelatedAppointmentId")
                        .HasConstraintName("FK_PatientHealthReminders_Appointment");

                    b.Navigation("RelatedAppointment");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Prescription", b =>
                {
                    b.HasOne("Medix.API.Data.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Prescriptions_MedicalRecord");

                    b.HasOne("Medix.API.Data.Models.MedicationDatabase", "Medication")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicationId")
                        .HasConstraintName("FK_Prescriptions_Medication");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Medix.API.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Review", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("Medix.API.Data.Models.Review", "AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Appointment");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Wallet", b =>
                {
                    b.HasOne("Medix.API.Data.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Medix.API.Data.Models.Wallet", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Wallets_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medix.API.Data.Models.WalletTransaction", b =>
                {
                    b.HasOne("Medix.API.Data.Models.Appointment", "RelatedAppointment")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("RelatedAppointmentId")
                        .HasConstraintName("FK_WalletTransactions_Appointment");

                    b.HasOne("Medix.API.Data.Models.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FK_WalletTransactions_Wallet");

                    b.Navigation("RelatedAppointment");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Medix.API.Data.Models.AisymptomAnalysis", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");

                    b.Navigation("PatientHealthReminders");

                    b.Navigation("Review");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.ContentCategory", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorAdCampaigns");

                    b.Navigation("DoctorPerformanceMetrics");

                    b.Navigation("DoctorSalaries");

                    b.Navigation("DoctorScheduleOverrides");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("DoctorSubscriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.DoctorServiceTier", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicalRecord", b =>
                {
                    b.Navigation("MedicalRecordAttachments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.MedicationDatabase", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Patient", b =>
                {
                    b.Navigation("AisymptomAnalyses");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medix.API.Data.Models.ServicePackage", b =>
                {
                    b.Navigation("DoctorSubscriptions");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Specialization", b =>
                {
                    b.Navigation("AisymptomAnalyses");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Medix.API.Data.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Cmspages");

                    b.Navigation("Doctor");

                    b.Navigation("HealthArticles");

                    b.Navigation("MedicalRecordAttachments");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Medix.API.Data.Models.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
